type Game {
  date: Time
  start: Time
  stop: Time
  won: Boolean
  lost: Boolean
  completed: Boolean
  time: Int
  moves: Int
  gameNumber: Int
  user: User
}

type AuthUser {
  uid: String!
  users: [User] @relation
}

type User {
  uid: String @unique
  authUser: AuthUser @relation
  games: [Game] @relation
}

type GlobalStats @embedded {
  count: Int!
}

type UserLID @embedded {
  uid: ID
}

input GameInput {
  won: Boolean
  lost: Boolean
  completed: Boolean
  moves: Int
  time: Int
}

type UserStats @embedded {
  count: Int
  won: Int
  lost: Int
  completed: Int
}

type Query {
  globalStats: GlobalStats! @resolver(name: "globalStats")
  findUserByLID(uid: String!): UserLID @resolver(name: "findUserByLID")
  userStats(uid: String!): UserStats! @resolver(name: "userStats")
}

type Mutation {
  newGame(uid: String!): Game! @resolver(name: "newGame")
}
