type Game {
  date: Time
  start: Time
  stop: Time
  won: Boolean
  lost: Boolean
  completed: Boolean
  time: Int
  moves: Int
  gameNumber: Int
  user: User
}

type AuthUser {
  uid: String!
  users: [User] @relation
}

type User {
  uid: String @unique
  authUser: AuthUser @relation 
  games: [Game] @relation
}

type totalGames @embedded {
  count: Int!
}

type userLID @embedded {
  uid: ID
}

input GameInput {
  won: Boolean
  lost: Boolean
  completed: Boolean
  moves: Int
  time: Int
}

type Query {
  totalGames: totalGames! @resolver(name: "totalGames")
  findUserByLID(uid: String!): userLID @resolver(name: "findUserByLID")
}

type Mutation {
  newGame(uid: String!): Game! @resolver(name: "newGame")
}
